### PR TITLE
Add Puma plugin

### PR DESCRIPTION
**Pull request by jacob-carlborg-apoex**
This manages the Dartsass watch process from `rails server`.

Most of this is taken from https://github.com/rails/tailwindcss-rails.

### CODE REVIEW

**Comment by northeastprince** [comment]
@dhh could we get this merged?

**Comment by dhh** [comment]
We've doubled down on bin/dev using foreman to do this. Appreciate the work, but I don't think there's enough of a benefit from adding this to warrant the confusion of when you should use this vs another.

**Comment by northeastprince** [comment]
There doesn't seem to be a way to do that with puma-dev

**Comment by jacob-carlborg-apoex** [comment]
> We've doubled down on bin/dev using foreman to do this

I prefer using Puma plugins in favor of Foreman. Then I don't need to use remote debugging to set a breakpoint.

**Pull request closed without merging**
